### ISSUE TITLE
All your code lives in the global scope

### ISSUE THREAD

**Issue by joostf** [deannabosschert/web-app-from-scratch-1920#13]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/60dc00604faefafcba92a9b94240f302ccef174e/docs/js/app.js#L1-L60

**Comment by deannabosschert** [comment]
I was highly aware of this haha (shedding a tear everytime I looked it at), but didn't want to change it until I fixed my routing/localStorage, otherwise I'd be doing three things at the same time as always.  Did put it into my 'To-do'-list in the readMe though. During my next project I will start by writing down the functions first instead :)

![fixed it, gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
